name: CI [pre-commit checks]

on:
  push: # this triggers on push events on all branches
  pull_request:
    branches: [ master ]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # Python setup
      # -------------------------

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/home/algo-visual-lab" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"

      - name: Create virtual environment
        run: |
          python -m venv .venv

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangocairo-1.0-0 libpango1.0-dev

      - name: Install dependencies
        shell: bash
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r manim/requirements.txt


      # -------------------------
      # Python and JS pre-commit
      # -------------------------

      - name: Run pre-commit (linting/formatting/mypy etc)
        shell: bash -l {0}
        run: |
          source .venv/bin/activate
          pre-commit run --all-files --show-diff-on-failure
